import { useState, useRef, useCallback, useEffect } from "react";
import * as XLSX from "xlsx";
import { X, Cloud, Download, Upload, Save, AlertCircle, CheckCircle, Loader, Plus, Trash2, FileSpreadsheet } from "lucide-react";
import { bulkCreateContractors } from "../contractors/api";
import type { Contractor } from "../contractors/types";

/* ─── Types ─────────────────────────────────────────────── */
interface RowData {
  contractNo:      string;
  contractYear:    string;
  contractor:      string;
  project:         string;
  portfolio:       string;
  mainActivity:    string;
  businessProgram: string;
  workFamily:      string;
  workType:        string;
  itemScope:       string;
  techSpecs:       string;
  measurements:    string;
  itemCode:        string;
  technicalScope:  string;
  workCategory:    string;
  unit:            string;
  price:           string;
  localContent:    string;
  phone:           string;
  email:           string;
  rating:          string;
}

type RowStatus = "idle" | "saving" | "saved" | "duplicate" | "error";

interface Row {
  id:     string;
  data:   RowData;
  status: RowStatus;
  error?: string;
}

interface Props {
  existingContractors: Contractor[];
  onClose:             () => void;
  onSaved:             () => void;
}

/* ─── Columns definition — order matches the main table ─── */
const COLUMNS: { key: keyof RowData; label: string; width: number; type?: "number" | "dropdown"; options?: string[] }[] = [
  { key: "contractNo",      label: "رقم العقد",        width: 55  },
  { key: "contractYear",    label: "سنة",              width: 34  },
  { key: "contractor",      label: "المقاول / المورد", width: 100 },
  { key: "project",         label: "المشروع",          width: 85  },
  { key: "portfolio",       label: "المحفظة",          width: 40  },
  { key: "mainActivity",    label: "النشاط",           width: 70  },
  { key: "businessProgram", label: "برنامج",           width: 65  },
  { key: "workFamily",      label: "عائلة",            width: 65  },
  { key: "workType",        label: "نوع الأعمال",      width: 60  },
  { key: "itemScope",       label: "شمولية",           width: 60  },
  { key: "techSpecs",       label: "مواصفات",          width: 60  },
  { key: "measurements",    label: "قياسات",           width: 35  },
  /* itemCode column intentionally NOT editable — server generates it. */
  { key: "technicalScope",  label: "الوصف الفني",      width: 110 },
  { key: "workCategory",    label: "تعاقد",            width: 42  },
  { key: "unit",            label: "وحدة",             width: 30  },
  { key: "price",           label: "السعر",            width: 52, type: "number" },
  { key: "localContent",    label: "محتوى محلي",       width: 50, type: "dropdown", options: ["", "مسجل", "غير مسجل"] },
  { key: "phone",           label: "التواصل",          width: 65  },
  { key: "email",           label: "البريد",           width: 88  },
  { key: "rating",          label: "تقييم",            width: 34, type: "number" },
];

/* ─── Helpers ───────────────────────────────────────────── */
function emptyRow(): Row {
  return {
    id: Math.random().toString(36).slice(2),
    status: "idle",
    data: {
      contractNo: "", contractYear: "", contractor: "", project: "", portfolio: "",
      mainActivity: "", businessProgram: "", workFamily: "",
      workType: "", itemScope: "", techSpecs: "", measurements: "", itemCode: "",
      technicalScope: "", workCategory: "", unit: "", price: "",
      localContent: "", phone: "", email: "", rating: "",
    },
  };
}

function makeRows(n: number): Row[] {
  return Array.from({ length: n }, emptyRow);
}

function isRowEmpty(r: RowData): boolean {
  return Object.values(r).every((v) => !v.trim());
}

/* Column order in paste / template (itemCode is auto-generated by the
   server, so it is NOT part of the user-facing template or entry grid):
   0:contractNo 1:contractYear 2:contractor 3:project 4:portfolio
   5:mainActivity 6:businessProgram 7:workFamily 8:workType
   9:itemScope 10:techSpecs 11:measurements
   12:technicalScope 13:workCategory 14:unit 15:price
   16:localContent 17:phone 18:email 19:rating */
/* ─── Column headers (order must match RowData exactly) ─── */
const TEMPLATE_HEADERS = [
  "رقم العقد", "سنة العقد", "المقاول / المورد", "المشروع", "المحفظة",
  "النشاط الرئيسي", "برنامج الأعمال", "عائلة الأعمال", "نوع الأعمال",
  "شمولية البند", "مواصفات فنية", "قياسات",
  "الوصف الفني للبند", "نوع التعاقد", "الوحدة", "السعر",
  "المحتوى المحلي", "رقم التواصل", "البريد الإلكتروني", "التقييم (0-5)",
];

function downloadTemplate() {
  const wb = XLSX.utils.book_new();
  const ws = XLSX.utils.aoa_to_sheet([TEMPLATE_HEADERS]);
  /* Style: wide columns + RTL */
  ws["!cols"] = TEMPLATE_HEADERS.map((h) => ({ wch: Math.max(h.length + 4, 14) }));
  (ws as any)["!dir"] = "rtl";
  XLSX.utils.book_append_sheet(wb, ws, "البيانات");
  XLSX.writeFile(wb, "قالب_إدخال_البيانات.xlsx");
}

function parseExcelFile(
  file: File,
  onProgress?: (percent: number, phase: "read" | "parse" | "done", rowCount?: number) => void,
): Promise<RowData[]> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    /* Phase 1 (0-70%): browser reading bytes from disk to memory. */
    reader.onprogress = (ev) => {
      if (onProgress && ev.lengthComputable && ev.total > 0) {
        const pct = Math.min(70, Math.round((ev.loaded / ev.total) * 70));
        onProgress(pct, "read");
      }
    };
    reader.onload = (e) => {
      try {
        onProgress?.(75, "parse");
        const data = e.target?.result;
        const wb = XLSX.read(data, { type: "array" });
        onProgress?.(90, "parse");
        const ws = wb.Sheets[wb.SheetNames[0]];
        const rows: string[][] = XLSX.utils.sheet_to_json(ws, { header: 1, defval: "" }) as string[][];
        /* Skip header row if first row matches template headers */
        const firstRow = rows[0]?.map((c) => String(c).trim()) ?? [];
        const hasHeader = firstRow.some((c) => TEMPLATE_HEADERS.includes(c));
        const dataRows = hasHeader ? rows.slice(1) : rows;
        const parsed: RowData[] = dataRows
          .filter((row) => row.some((c) => String(c).trim()))
          .map((cells) => {
            const get = (i: number) => String(cells[i] ?? "").trim();
            return {
              contractNo:      get(0),  contractYear:    get(1),
              contractor:      get(2),  project:         get(3),
              portfolio:       get(4),  mainActivity:    get(5),
              businessProgram: get(6),  workFamily:      get(7),
              workType:        get(8),  itemScope:       get(9),
              techSpecs:       get(10), measurements:    get(11),
              /* itemCode is auto-generated by the server — always empty here. */
              itemCode:        "",
              technicalScope:  get(12), workCategory:    get(13),
              unit:            get(14), price:           get(15),
              localContent:    get(16), phone:           get(17),
              email:           get(18), rating:          get(19),
            };
          });
        /* Pass the final row count so the UI can show an animated counter. */
        onProgress?.(100, "done", parsed.length);
        resolve(parsed);
      } catch (err) {
        reject(err);
      }
    };
    reader.onerror = reject;
    reader.readAsArrayBuffer(file);
  });
}

function parsePasted(text: string): RowData[] {
  const lines = text.replace(/\r\n/g, "\n").replace(/\r/g, "\n").split("\n").filter((l) => l.trim());
  return lines.map((line) => {
    const cells = line.split("\t").map((c) => c.trim());
    const get = (i: number) => cells[i] ?? "";
    return {
      contractNo:      get(0),
      contractYear:    get(1),
      contractor:      get(2),
      project:         get(3),
      portfolio:       get(4),
      mainActivity:    get(5),
      businessProgram: get(6),
      workFamily:      get(7),
      workType:        get(8),
      itemScope:       get(9),
      techSpecs:       get(10),
      measurements:    get(11),
      /* itemCode is auto-generated by the server — never accepted from paste. */
      itemCode:        "",
      technicalScope:  get(12),
      workCategory:    get(13),
      unit:            get(14),
      price:           get(15),
      localContent:    get(16),
      phone:           get(17),
      email:           get(18),
      rating:          get(19),
    };
  });
}

/* ─── Full-record duplicate detection ───────────────────────
   A record is a duplicate ONLY when ALL key columns match an
   existing DB record exactly (localContent & rating excluded).
   ──────────────────────────────────────────────────────────── */
function norm(s: string): string {
  return (s ?? "").replace(/[\u064B-\u065F]/g, "").replace(/[أإآ]/g, "ا").replace(/ة/g, "ه").replace(/ى/g, "ي").toLowerCase().trim();
}

function dbSignature(c: Contractor): string {
  return [
    norm(c.contractNo),
    norm(c.contractYear     ?? ""),
    norm(c.contractor),
    norm(c.project),
    norm(c.portfolio),
    norm(c.mainActivity     ?? ""),
    norm(c.businessProgram  ?? ""),
    norm(c.workFamily       ?? ""),
    norm(c.workType),
    norm(c.itemScope        ?? ""),
    norm(c.techSpecs        ?? ""),
    norm(c.measurements     ?? ""),
    /* itemCode excluded from duplicate signature — server regenerates it. */
    norm(c.technicalScope),
    norm(c.workCategory     ?? ""),
    norm(c.unit             ?? ""),
    String(c.price),
    norm(c.phone),
    norm(c.email),
  ].join("\x00");
}

function rowSignature(d: RowData): string {
  return [
    norm(d.contractNo),
    norm(d.contractYear),
    norm(d.contractor),
    norm(d.project),
    norm(d.portfolio),
    norm(d.mainActivity),
    norm(d.businessProgram),
    norm(d.workFamily),
    norm(d.workType),
    norm(d.itemScope),
    norm(d.techSpecs),
    norm(d.measurements),
    /* itemCode excluded from duplicate signature — server regenerates it. */
    norm(d.technicalScope),
    norm(d.workCategory),
    norm(d.unit),
    String(Math.round(parseFloat(d.price) || 0)),
    norm(d.phone),
    norm(d.email),
  ].join("\x00");
}

/* ─── Status Badge ──────────────────────────────────────── */
function StatusBadge({ status, error }: { status: RowStatus; error?: string }) {
  if (status === "idle")      return null;
  if (status === "saving")    return <Loader size={14} style={{ color: "#3b8fcc", animation: "spin-loader 0.9s linear infinite" }} />;
  if (status === "saved")     return <CheckCircle size={14} style={{ color: "#2baa74" }} />;
  if (status === "duplicate") return (
    <span title="سجل مطابق تماماً موجود في القاعدة — تم التخطي">
      <AlertCircle size={14} style={{ color: "#e67e22" }} />
    </span>
  );
  return (
    <span title={error}>
      <AlertCircle size={14} style={{ color: "#e74c3c" }} />
    </span>
  );
}

/* ─── Main Component ─────────────────────────────────────── */
export default function CloudSyncModal({ existingContractors, onClose, onSaved }: Props) {
  const [rows, setRows] = useState<Row[]>(() => makeRows(10));
  const [isSaving, setIsSaving] = useState(false);
  const [saveProgress, setSaveProgress] = useState<{ saved: number; total: number } | null>(null);
  const [saveResult, setSaveResult] = useState<{ saved: number; total: number; errors: number; firstError: string | null; duplicates?: number } | null>(null);
  const [summary, setSummary] = useState<{ saved: number; duplicates: number; errors: number } | null>(null);
  const [templateMode, setTemplateMode] = useState(false);
  const [uploadError, setUploadError] = useState<string | null>(null);
  const [uploadName, setUploadName] = useState<string | null>(null);
  const [isReading, setIsReading] = useState(false);
  const [readProgress, setReadProgress] = useState(0);
  const [readPhase, setReadPhase] = useState<"read" | "parse" | "done" | null>(null);
  const [readTotalRows, setReadTotalRows] = useState(0);
  const [readDisplayRows, setReadDisplayRows] = useState(0);
  const fileInputRef = useRef<HTMLInputElement>(null);

  /* Animate row counter from 0 → readTotalRows when parsing finishes */
  useEffect(() => {
    if (readTotalRows === 0) { setReadDisplayRows(0); return; }
    let current = 0;
    const step  = Math.max(1, Math.ceil(readTotalRows / 60)); // ~60 frames
    const id = setInterval(() => {
      current += step;
      if (current >= readTotalRows) { setReadDisplayRows(readTotalRows); clearInterval(id); }
      else { setReadDisplayRows(current); }
    }, 16); // ~60 fps
    return () => clearInterval(id);
  }, [readTotalRows]);

  const existingSignatures = new Set(existingContractors.map(dbSignature));

  const updateCell = useCallback((rowId: string, key: keyof RowData, value: string) => {
    setRows((prev) => prev.map((r) =>
      r.id === rowId ? { ...r, data: { ...r.data, [key]: value }, status: "idle", error: undefined } : r
    ));
  }, []);

  function addRows(n = 5) {
    setRows((prev) => [...prev, ...makeRows(n)]);
  }

  function removeRow(rowId: string) {
    setRows((prev) => prev.filter((r) => r.id !== rowId));
  }

  async function handleFileUpload(file: File) {
    setUploadError(null);
    setIsReading(true);
    setReadProgress(0);
    setReadPhase("read");
    setReadTotalRows(0);
    setReadDisplayRows(0);
    setUploadName(file.name);
    try {
      const parsed = await parseExcelFile(file, (pct, phase, rowCount) => {
        setReadProgress(pct);
        setReadPhase(phase);
        if (phase === "done" && rowCount != null) setReadTotalRows(rowCount);
      });
      if (parsed.length === 0) { setUploadError("لم يتم العثور على بيانات في الملف"); setIsReading(false); setReadProgress(0); return; }
      const newRows: Row[] = parsed.map((data) => ({ id: Math.random().toString(36).slice(2), data, status: "idle" }));
      setRows((prev) => {
        const nonEmpty = prev.filter((r) => !isRowEmpty(r.data));
        return [...nonEmpty, ...newRows, ...makeRows(Math.max(0, 3))];
      });
      setTemplateMode(false);
      setUploadName(null);
    } catch {
      setUploadError("تعذّر قراءة الملف — تأكد أنه ملف Excel صحيح (.xlsx / .xls)");
    } finally {
      setIsReading(false);
      setReadProgress(0);
      setReadPhase(null);
      setReadTotalRows(0);
      setReadDisplayRows(0);
      if (fileInputRef.current) fileInputRef.current.value = "";
    }
  }

  async function handleSave() {
    const toSave = rows.filter((r) => !isRowEmpty(r.data));
    if (toSave.length === 0) return;

    setIsSaving(true);
    setSummary(null);
    setSaveResult(null);

    /* ── Phase 1: PURE duplicate detection (no side effects in setState). ──
       Compute the duplicate vs fresh split first, then issue a single
       deterministic setRows. */
    const duplicateIds = new Set<string>();
    const fresh: Row[] = [];
    for (const r of toSave) {
      if (existingSignatures.has(rowSignature(r.data))) {
        duplicateIds.add(r.id);
      } else {
        fresh.push(r);
      }
    }
    const duplicates = duplicateIds.size;
    const freshIds = new Set(fresh.map((r) => r.id));
    setRows((prev) =>
      prev.map((r) => {
        if (duplicateIds.has(r.id)) return { ...r, status: "duplicate" };
        if (freshIds.has(r.id))     return { ...r, status: "saving" };
        return r;
      })
    );

    if (fresh.length === 0) {
      /* All inputs were duplicates — surface this clearly via the locked
         result overlay so the user does not miss the outcome. */
      setSummary({ saved: 0, duplicates, errors: 0 });
      setSaveResult({ saved: 0, total: 0, errors: 0, firstError: null, duplicates });
      return;
    }

    /* ── Phase 2: build the payload ONCE (in memory) ── */
    const payload = fresh.map((row) => ({
      contractNo:      row.data.contractNo.trim(),
      contractYear:    row.data.contractYear.trim()    || null,
      contractor:      row.data.contractor.trim(),
      project:         row.data.project.trim(),
      portfolio:       row.data.portfolio.trim(),
      mainActivity:    row.data.mainActivity.trim()    || null,
      businessProgram: row.data.businessProgram.trim() || null,
      workFamily:      row.data.workFamily.trim()      || null,
      workType:        row.data.workType.trim(),
      itemScope:       row.data.itemScope.trim()       || null,
      techSpecs:       row.data.techSpecs.trim()       || null,
      measurements:    row.data.measurements.trim()    || null,
      /* itemCode is ALWAYS server-generated — discard any inbound value. */
      itemCode:        null,
      technicalScope:  row.data.technicalScope.trim(),
      workCategory:    row.data.workCategory.trim()    || null,
      unit:            row.data.unit.trim()            || null,
      price:           Math.min(Math.round(parseFloat(row.data.price) || 0), 2_000_000_000),
      localContent:    row.data.localContent.trim()    || null,
      phone:           row.data.phone.trim(),
      email:           row.data.email.trim(),
      rating:          row.data.rating ? Math.min(5, Math.max(0, Math.round(parseFloat(row.data.rating)))) : null,
      workDescription: null,
      workScopeText:   null,
    }));

    /* ── Phase 3: chunked incremental save ──
       Each 500-row chunk is its own HTTP request and its own DB
       transaction.  Server-side COMMIT happens after every chunk, so if
       the user closes the browser mid-import every chunk already
       acknowledged is permanently persisted.  Live progress UI updates
       between chunks. */
    const CHUNK_SIZE = 500;
    setSaveProgress({ saved: 0, total: payload.length });

    let saved = 0;
    let errors = 0;
    let firstError: string | null = null;
    const savedIds: string[] = [];

    for (let i = 0; i < payload.length; i += CHUNK_SIZE) {
      const sliceItems  = payload.slice(i, i + CHUNK_SIZE);
      const sliceRows   = fresh.slice(i, i + CHUNK_SIZE);
      try {
        const result = await bulkCreateContractors(sliceItems);
        saved += result.saved;
        for (const r of sliceRows) {
          existingSignatures.add(rowSignature(r.data));
          savedIds.push(r.id);
        }
        const savedIdSet = new Set(savedIds);
        setRows((prev) => prev.map((r) =>
          savedIdSet.has(r.id) ? { ...r, status: "saved" } : r
        ));
        setSaveProgress({ saved, total: payload.length });
        /* Yield to the browser so the progress UI repaints between chunks
           before we kick off the next network round-trip. */
        await new Promise((resolve) => setTimeout(resolve, 0));
      } catch (e: unknown) {
        const msg = e instanceof Error ? e.message : "خطأ غير معروف";
        if (!firstError) firstError = msg;
        errors += sliceRows.length;
        const failedIds = new Set(sliceRows.map((r) => r.id));
        setRows((prev) => prev.map((r) =>
          failedIds.has(r.id) ? { ...r, status: "error", error: msg } : r
        ));
        /* Stop on first failure — saved chunks are already persisted in
           data.db so the user keeps the work that succeeded. */
        break;
      }
    }

    /* Safety net: any row still flagged "saving" after the loop is a bug
       in our accounting (should be impossible). Force it to "error" so the
       UI never shows an indefinite spinner next to a row. */
    setRows((prev) => prev.map((r) =>
      r.status === "saving"
        ? { ...r, status: "error", error: "لم يكتمل الحفظ — أعد المحاولة" }
        : r
    ));

    setSummary({ saved, duplicates, errors });
    /* Keep the overlay locked AND switch it to the final result screen.
       The user must press "تم" to dismiss — so even a 500ms import is
       clearly acknowledged with a checkmark + count, instead of vanishing
       before the eye can register it. */
    setSaveResult({ saved, total: payload.length, errors, firstError, duplicates });
    setSaveProgress(null);
    if (saved > 0) onSaved();
  }

  const nonEmptyCount = rows.filter((r) => !isRowEmpty(r.data)).length;

  return (
    <div style={{ position: "fixed", inset: 0, zIndex: 2000, background: "rgba(10,8,5,0.72)", backdropFilter: "blur(6px)", display: "flex", flexDirection: "column" }}>
      {/* ── Header ── */}
      <div style={{ background: "linear-gradient(135deg, #0d1f3c 0%, #1a3a5c 100%)", borderBottom: "2px solid rgba(59,143,204,0.4)", padding: "14px 24px", display: "flex", alignItems: "center", gap: "14px", flexShrink: 0, direction: "rtl" }}>
        <div style={{ display: "flex", alignItems: "center", gap: "10px", flex: 1 }}>
          <div style={{ width: 36, height: 36, borderRadius: "10px", background: "linear-gradient(135deg, #1e6fa8, #3b8fcc)", display: "flex", alignItems: "center", justifyContent: "center", boxShadow: "0 4px 14px rgba(59,143,204,0.4)" }}>
            <Cloud size={18} color="#fff" />
          </div>
          <div>
            <div style={{ fontSize: "0.9rem", fontWeight: 800, color: "#fff", lineHeight: 1.2 }}>إدخال بيانات سحابي</div>
            <div style={{ fontSize: "0.62rem", color: "rgba(59,143,204,0.85)", letterSpacing: "0.08em", textTransform: "uppercase" }}>Excel Online Sync · Cloud Database Entry — 20 عموداً</div>
          </div>
        </div>
        <div style={{ display: "flex", gap: "8px", alignItems: "center" }}>
          <span style={{ background: "rgba(59,143,204,0.18)", border: "1px solid rgba(59,143,204,0.35)", borderRadius: "20px", padding: "4px 12px", fontSize: "0.72rem", color: "#7ec8f0", fontWeight: 700 }}>{rows.length} صف</span>
          <span style={{ background: "rgba(43,170,116,0.15)", border: "1px solid rgba(43,170,116,0.3)", borderRadius: "20px", padding: "4px 12px", fontSize: "0.72rem", color: "#5dd6a8", fontWeight: 700 }}>{nonEmptyCount} مدخل</span>
        </div>
        <div style={{ display: "flex", gap: "8px", alignItems: "center" }}>
          <button onClick={() => setTemplateMode(true)} style={{ display: "flex", alignItems: "center", gap: "6px", background: "rgba(59,143,204,0.15)", border: "1.5px solid rgba(59,143,204,0.4)", color: "#7ec8f0", borderRadius: "9px", padding: "7px 14px", fontSize: "0.78rem", fontWeight: 700, cursor: "pointer", fontFamily: "Tajawal, sans-serif" }}>
            <FileSpreadsheet size={13} />
            قالب / رفع Excel
          </button>
          <button onClick={handleSave} disabled={isSaving || nonEmptyCount === 0} style={{ display: "flex", alignItems: "center", gap: "6px", background: isSaving || nonEmptyCount === 0 ? "rgba(59,143,204,0.25)" : "linear-gradient(135deg, #1e6fa8, #3b8fcc)", border: "none", color: "#fff", borderRadius: "9px", padding: "8px 18px", fontSize: "0.82rem", fontWeight: 700, cursor: isSaving || nonEmptyCount === 0 ? "not-allowed" : "pointer", fontFamily: "Tajawal, sans-serif", boxShadow: isSaving || nonEmptyCount === 0 ? "none" : "0 4px 14px rgba(59,143,204,0.4)", opacity: isSaving || nonEmptyCount === 0 ? 0.6 : 1 }}>
            {isSaving ? <Loader size={13} style={{ animation: "spin-loader 0.9s linear infinite" }} /> : <Save size={13} />}
            {isSaving ? "جاري الحفظ..." : `حفظ (${nonEmptyCount})`}
          </button>
          <button onClick={onClose} style={{ background: "rgba(255,255,255,0.08)", border: "1px solid rgba(255,255,255,0.15)", color: "#aaa", borderRadius: "8px", padding: "7px 10px", cursor: "pointer" }}>
            <X size={16} />
          </button>
        </div>
      </div>

      {/* ── Summary Banner ── */}
      {summary && (
        <div style={{ background: summary.errors > 0 ? "rgba(231,76,60,0.12)" : summary.duplicates > 0 ? "rgba(230,126,34,0.12)" : "rgba(43,170,116,0.12)", borderBottom: `1px solid ${summary.errors > 0 ? "rgba(231,76,60,0.3)" : summary.duplicates > 0 ? "rgba(230,126,34,0.3)" : "rgba(43,170,116,0.3)"}`, padding: "10px 24px", fontSize: "0.8rem", fontWeight: 700, color: summary.errors > 0 ? "#e74c3c" : summary.duplicates > 0 ? "#e67e22" : "#2baa74", display: "flex", gap: "20px", alignItems: "center", direction: "rtl", flexShrink: 0 }}>
          <span>✅ تم حفظ {summary.saved} سجل</span>
          {summary.duplicates > 0 && <span>⚠️ {summary.duplicates} مكرر (تم تخطيه)</span>}
          {summary.errors > 0 && <span>❌ {summary.errors} خطأ في الحفظ</span>}
          {summary.saved > 0 && <span style={{ marginRight: "auto", fontSize: "0.72rem", color: "#aaa", fontWeight: 400 }}>تم تحديث قاعدة البيانات السحابية بنجاح</span>}
        </div>
      )}

      {/* ── Instructions bar ── */}
      <div style={{ background: "#0a1628", padding: "8px 24px", fontSize: "0.68rem", color: "rgba(126,200,240,0.7)", display: "flex", gap: "20px", alignItems: "center", direction: "rtl", flexShrink: 0, borderBottom: "1px solid rgba(59,143,204,0.15)" }}>
        <span>💡 انقر على أي خلية لتعديلها مباشرة</span>
        <span>📋 الترتيب عند اللصق: رقم العقد | سنة العقد | المقاول | المشروع | المحفظة | النشاط | برنامج | عائلة | نوع الأعمال | شمولية | مواصفات | قياسات | وصف فني | تعاقد | وحدة | سعر | محتوى محلي | تواصل | بريد | تقييم</span>
        <span>🔒 السجل المكرر بجميع بياناته يُتخطى</span>
      </div>

      {/* ── Grid ── */}
      <div className="dark-scroll" style={{ flex: 1, overflowY: "auto", overflowX: "clip", background: "#0d1a2e" }}>
        <table style={{ borderCollapse: "collapse", tableLayout: "fixed", direction: "rtl", width: "100%" }}>
          <colgroup>
            <col style={{ width: 36 }} />
            {COLUMNS.map((c) => <col key={c.key} style={{ width: c.width }} />)}
            <col style={{ width: 54 }} />
          </colgroup>

          <thead style={{ position: "sticky", top: 0, zIndex: 10 }}>
            <tr style={{ background: "#0a1525", borderBottom: "2px solid rgba(59,143,204,0.35)" }}>
              <th style={{ padding: "9px 6px", fontSize: "0.6rem", color: "rgba(59,143,204,0.5)", textAlign: "center", borderLeft: "1px solid rgba(59,143,204,0.1)" }}>#</th>
              {COLUMNS.map((c) => (
                <th key={c.key} style={{ padding: "6px 4px", fontSize: "0.58rem", fontWeight: 700, color: "rgba(59,143,204,0.9)", textAlign: "right", letterSpacing: "0.02em", whiteSpace: "normal", wordBreak: "break-word", lineHeight: 1.2, verticalAlign: "bottom", borderLeft: "1px solid rgba(59,143,204,0.12)" }}>
                  {c.label}
                </th>
              ))}
              <th style={{ padding: "9px 6px", fontSize: "0.6rem", color: "rgba(59,143,204,0.5)", textAlign: "center" }}>حالة</th>
            </tr>
          </thead>

          <tbody>
            {rows.map((row, idx) => {
              const isEmpty = isRowEmpty(row.data);
              const isDup   = row.status === "duplicate";
              const isSaved = row.status === "saved";
              const isErr   = row.status === "error";
              const rowBg   = isSaved ? "rgba(43,170,116,0.07)" : isDup ? "rgba(230,126,34,0.07)" : isErr ? "rgba(231,76,60,0.07)" : idx % 2 === 0 ? "#0f1f38" : "#0d1b33";
              return (
                <tr key={row.id} style={{ background: rowBg, borderBottom: "1px solid rgba(59,143,204,0.08)" }}>
                  <td style={{ padding: "3px 6px", fontSize: "0.6rem", color: "rgba(59,143,204,0.4)", textAlign: "center", borderLeft: "1px solid rgba(59,143,204,0.08)", verticalAlign: "middle" }}>
                    {isEmpty ? <span style={{ color: "rgba(59,143,204,0.2)" }}>·</span> : idx + 1}
                  </td>
                  {COLUMNS.map((col) => (
                    <td key={col.key} style={{ padding: "2px 3px", borderLeft: "1px solid rgba(59,143,204,0.08)", verticalAlign: "middle" }}>
                      {col.type === "dropdown" ? (
                        <select value={row.data[col.key]} onChange={(e) => updateCell(row.id, col.key, e.target.value)} disabled={isSaved}
                          style={{ width: "100%", background: "transparent", border: "none", color: isSaved ? "#2baa74" : isDup ? "#e67e22" : "#c8dff0", fontSize: "0.72rem", fontFamily: "Tajawal, sans-serif", outline: "none", cursor: isSaved ? "not-allowed" : "pointer", padding: "5px 4px", direction: "rtl" }}>
                          {(col.options ?? []).map((opt) => <option key={opt} value={opt} style={{ background: "#0d1f3c" }}>{opt || "— اختر —"}</option>)}
                        </select>
                      ) : (
                        <input type={col.type === "number" ? "number" : "text"} value={row.data[col.key]} onChange={(e) => updateCell(row.id, col.key, e.target.value)} disabled={isSaved} min={col.type === "number" ? 0 : undefined}
                          style={{ width: "100%", background: "transparent", border: "none", color: isSaved ? "#2baa74" : isDup ? "#e67e22" : isErr ? "#e74c3c" : "#c8dff0", fontSize: "0.72rem", fontFamily: "Tajawal, sans-serif", outline: "none", padding: "5px 6px", direction: "rtl", cursor: isSaved ? "not-allowed" : "text" }}
                          onFocus={(e) => { if (!isSaved) { (e.target.parentElement as HTMLElement).style.background = "rgba(59,143,204,0.12)"; (e.target.parentElement as HTMLElement).style.borderRadius = "4px"; } }}
                          onBlur={(e) => { (e.target.parentElement as HTMLElement).style.background = ""; }}
                        />
                      )}
                    </td>
                  ))}
                  <td style={{ padding: "3px 6px", textAlign: "center", verticalAlign: "middle", borderLeft: "1px solid rgba(59,143,204,0.08)" }}>
                    <div style={{ display: "flex", alignItems: "center", justifyContent: "center", gap: "4px" }}>
                      <StatusBadge status={row.status} error={row.error} />
                      {!isSaved && (
                        <button onClick={() => removeRow(row.id)} style={{ background: "none", border: "none", color: "rgba(231,76,60,0.4)", cursor: "pointer", padding: "2px", display: "flex", alignItems: "center" }} title="حذف الصف">
                          <Trash2 size={11} />
                        </button>
                      )}
                    </div>
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      {/* ── Footer ── */}
      <div style={{ background: "#0a1525", borderTop: "1px solid rgba(59,143,204,0.2)", padding: "10px 24px", display: "flex", gap: "12px", alignItems: "center", direction: "rtl", flexShrink: 0 }}>
        <button onClick={() => addRows(5)} style={{ display: "flex", alignItems: "center", gap: "6px", background: "rgba(59,143,204,0.12)", border: "1px solid rgba(59,143,204,0.3)", color: "#7ec8f0", borderRadius: "8px", padding: "7px 14px", fontSize: "0.78rem", fontWeight: 700, cursor: "pointer", fontFamily: "Tajawal, sans-serif" }}>
          <Plus size={13} />
          إضافة 5 صفوف
        </button>
        <button onClick={() => addRows(20)} style={{ display: "flex", alignItems: "center", gap: "6px", background: "rgba(59,143,204,0.08)", border: "1px solid rgba(59,143,204,0.2)", color: "rgba(126,200,240,0.7)", borderRadius: "8px", padding: "7px 14px", fontSize: "0.78rem", fontWeight: 700, cursor: "pointer", fontFamily: "Tajawal, sans-serif" }}>
          <Plus size={13} />
          إضافة 20 صفاً
        </button>
        <span style={{ marginRight: "auto", fontSize: "0.68rem", color: "rgba(59,143,204,0.5)" }}>
          {rows.filter((r) => r.status === "saved").length} محفوظ · {rows.filter((r) => r.status === "duplicate").length} مكرر · {rows.filter((r) => r.status === "error").length} خطأ
        </span>
      </div>

      {/* ── Template / Upload Overlay ── */}
      <input
        ref={fileInputRef}
        type="file"
        accept=".xlsx,.xls"
        style={{ display: "none" }}
        onChange={(e) => { const f = e.target.files?.[0]; if (f) handleFileUpload(f); }}
      />
      {templateMode && (
        <div style={{ position: "absolute", inset: 0, background: "rgba(5,12,28,0.88)", backdropFilter: "blur(8px)", zIndex: 100, display: "flex", alignItems: "center", justifyContent: "center", padding: "40px" }}>
          <div style={{ background: "#0d1f3c", border: "2px solid rgba(59,143,204,0.4)", borderRadius: "16px", padding: "32px", maxWidth: "580px", width: "100%", direction: "rtl" }}>
            {/* Header */}
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: "24px" }}>
              <div>
                <div style={{ fontSize: "1rem", fontWeight: 800, color: "#fff", marginBottom: "6px" }}>استيراد بيانات من Excel</div>
                <div style={{ fontSize: "0.7rem", color: "rgba(126,200,240,0.65)", lineHeight: 1.6 }}>حمّل القالب، عبّئه في Excel، ثم ارفعه لاستيراد البيانات تلقائياً</div>
              </div>
              <button onClick={() => { setTemplateMode(false); setUploadError(null); setUploadName(null); }} style={{ background: "none", border: "none", color: "#aaa", cursor: "pointer", flexShrink: 0 }}><X size={18} /></button>
            </div>

            {/* Step 1 — Download template */}
            <div style={{ background: "rgba(59,143,204,0.08)", border: "1px solid rgba(59,143,204,0.25)", borderRadius: "12px", padding: "18px 20px", marginBottom: "14px" }}>
              <div style={{ display: "flex", alignItems: "center", gap: "12px" }}>
                <div style={{ width: 36, height: 36, borderRadius: "10px", background: "linear-gradient(135deg, #1e6fa8, #3b8fcc)", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}>
                  <span style={{ fontSize: "0.85rem", fontWeight: 800, color: "#fff" }}>١</span>
                </div>
                <div style={{ flex: 1 }}>
                  <div style={{ fontSize: "0.82rem", fontWeight: 700, color: "#c8dff0", marginBottom: "3px" }}>تحميل القالب</div>
                  <div style={{ fontSize: "0.68rem", color: "rgba(126,200,240,0.6)" }}>ملف Excel جاهز بترتيب الأعمدة الصحيح (20 عمود — كود البند يُولَّد تلقائياً)</div>
                </div>
                <button onClick={downloadTemplate} style={{ display: "flex", alignItems: "center", gap: "6px", background: "linear-gradient(135deg, #1e6fa8, #3b8fcc)", border: "none", color: "#fff", borderRadius: "9px", padding: "9px 18px", fontSize: "0.8rem", fontWeight: 700, cursor: "pointer", fontFamily: "Tajawal, sans-serif", flexShrink: 0, boxShadow: "0 4px 14px rgba(59,143,204,0.35)" }}>
                  <Download size={14} />
                  تحميل القالب
                </button>
              </div>
            </div>

            {/* Step 2 — Upload filled file */}
            <div style={{ background: "rgba(43,170,116,0.08)", border: "1px solid rgba(43,170,116,0.25)", borderRadius: "12px", padding: "18px 20px", marginBottom: uploadError ? "12px" : "24px" }}>
              <div style={{ display: "flex", alignItems: "center", gap: "12px" }}>
                <div style={{ width: 36, height: 36, borderRadius: "10px", background: "linear-gradient(135deg, #1d8a5a, #2baa74)", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}>
                  <span style={{ fontSize: "0.85rem", fontWeight: 800, color: "#fff" }}>٢</span>
                </div>
                <div style={{ flex: 1, minWidth: 0 }}>
                  <div style={{ fontSize: "0.82rem", fontWeight: 700, color: "#a0e6c8", marginBottom: "3px", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>
                    {uploadName ? uploadName : "رفع الملف المعبّأ"}
                  </div>
                  {/* Status text */}
                  <div style={{ fontSize: "0.68rem", color: "rgba(100,220,170,0.7)", fontWeight: 600, minHeight: "1.2em" }}>
                    {isReading
                      ? readPhase === "read"
                        ? `جاري قراءة الملف... ${readProgress}%`
                        : readPhase === "parse"
                          ? `جاري تحليل البيانات... ${readProgress}%`
                          : readPhase === "done"
                            ? `اكتمل التحليل — جاري الإدراج...`
                            : `جاري المعالجة... ${readProgress}%`
                      : "اختر ملف Excel (.xlsx / .xls) بعد تعبئة القالب"}
                  </div>

                  {/* Animated row counter — appears when row count is known */}
                  {isReading && readTotalRows > 0 && (
                    <div style={{ display: "flex", alignItems: "center", gap: "6px", marginTop: "4px" }}>
                      <span style={{ fontSize: "0.62rem", color: "rgba(100,220,170,0.5)", fontFamily: "Tajawal, sans-serif" }}>تم رصد</span>
                      <span style={{
                        fontSize: "1rem", fontWeight: 900,
                        color: "#4dd49a",
                        fontFamily: "monospace",
                        letterSpacing: "-0.02em",
                        minWidth: "4ch",
                        textShadow: "0 0 12px rgba(77,212,154,0.5)",
                        transition: "color 0.1s",
                      }}>
                        {readDisplayRows.toLocaleString("ar-EG")}
                      </span>
                      <span style={{ fontSize: "0.62rem", color: "rgba(100,220,170,0.5)", fontFamily: "Tajawal, sans-serif" }}>
                        من {readTotalRows.toLocaleString("ar-EG")} سجل
                      </span>
                    </div>
                  )}

                  {/* Live progress bar */}
                  {isReading && (
                    <div style={{ marginTop: 6, width: "100%", height: 6, background: "rgba(43,170,116,0.15)", borderRadius: 999, overflow: "hidden", border: "1px solid rgba(43,170,116,0.25)" }}>
                      <div style={{
                        width: readTotalRows > 0
                          ? `${Math.round((readDisplayRows / readTotalRows) * 100)}%`
                          : `${readProgress}%`,
                        height: "100%",
                        background: "linear-gradient(90deg, #2baa74, #4dd49a)",
                        boxShadow: "0 0 10px rgba(43,170,116,0.6)",
                        transition: "width 0.06s linear",
                        borderRadius: 999,
                      }} />
                    </div>
                  )}
                </div>
                <button
                  onClick={() => { setUploadError(null); fileInputRef.current?.click(); }}
                  disabled={isReading}
                  style={{ display: "flex", alignItems: "center", gap: "6px", background: isReading ? "rgba(43,170,116,0.25)" : "linear-gradient(135deg, #1d8a5a, #2baa74)", border: "none", color: "#fff", borderRadius: "9px", padding: "9px 18px", fontSize: "0.8rem", fontWeight: 700, cursor: isReading ? "not-allowed" : "pointer", fontFamily: "Tajawal, sans-serif", flexShrink: 0, boxShadow: isReading ? "none" : "0 4px 14px rgba(43,170,116,0.3)", opacity: isReading ? 0.85 : 1, minWidth: 110, justifyContent: "center" }}>
                  {isReading ? (
                    <div style={{ display: "flex", flexDirection: "column", alignItems: "center", gap: "2px", lineHeight: 1 }}>
                      <Loader size={14} style={{ animation: "spin-loader 0.9s linear infinite" }} />
                      {readTotalRows > 0 ? (
                        <span style={{ fontFamily: "monospace", fontWeight: 900, fontSize: "0.9rem", letterSpacing: "-0.02em" }}>
                          {readDisplayRows.toLocaleString("ar-EG")}
                        </span>
                      ) : (
                        <span style={{ fontFamily: "monospace", fontWeight: 800 }}>{readProgress}%</span>
                      )}
                    </div>
                  ) : (
                    <>
                      <Upload size={14} />
                      رفع الملف
                    </>
                  )}
                </button>
              </div>
            </div>

            {/* Error */}
            {uploadError && (
              <div style={{ background: "rgba(231,76,60,0.1)", border: "1px solid rgba(231,76,60,0.3)", borderRadius: "8px", padding: "10px 14px", marginBottom: "16px", fontSize: "0.78rem", color: "#e74c3c", display: "flex", alignItems: "center", gap: "8px" }}>
                <AlertCircle size={14} />
                {uploadError}
              </div>
            )}

            <div style={{ textAlign: "center" }}>
              <button onClick={() => { setTemplateMode(false); setUploadError(null); setUploadName(null); }} style={{ background: "rgba(255,255,255,0.06)", border: "1px solid rgba(255,255,255,0.12)", color: "#aaa", borderRadius: "8px", padding: "8px 24px", fontSize: "0.8rem", fontWeight: 700, cursor: "pointer", fontFamily: "Tajawal, sans-serif" }}>إغلاق</button>
            </div>
          </div>
        </div>
      )}

      {/* ─── Bulk-save overlay ──────────────────────────────────────────
           Locks the entire modal during a bulk import so the user
           cannot double-click "حفظ" or close the dialog mid-flight.
           Shows row count + animated spinner.                          */}
      {(isSaving || saveResult) && (() => {
        const done       = saveResult !== null;
        const total      = saveResult?.total ?? saveProgress?.total ?? nonEmptyCount;
        const savedNow   = saveResult?.saved ?? saveProgress?.saved ?? 0;
        const percent    = total > 0 ? Math.min(100, Math.round((savedNow / total) * 100)) : 0;
        const arSaved    = savedNow.toLocaleString("ar-EG");
        const arTotal    = total.toLocaleString("ar-EG");
        const hasErrors  = (saveResult?.errors ?? 0) > 0;
        const fullSuccess = done && !hasErrors && savedNow === total && total > 0;
        return (
          <div
            role="status"
            aria-live="polite"
            style={{
              position: "fixed", inset: 0, zIndex: 3000,
              background: "rgba(8,14,28,0.82)", backdropFilter: "blur(12px)",
              display: "flex", flexDirection: "column",
              alignItems: "center", justifyContent: "center",
              gap: "22px", direction: "rtl",
              fontFamily: "Tajawal, sans-serif",
              animation: "fadeInUp 0.25s ease-out",
            }}
          >
            {done ? (
              <div style={{
                width: 92, height: 92, borderRadius: "50%",
                background: fullSuccess
                  ? "linear-gradient(135deg, #10b981 0%, #059669 100%)"
                  : hasErrors
                    ? "linear-gradient(135deg, #ef4444 0%, #b91c1c 100%)"
                    : "linear-gradient(135deg, #f59e0b 0%, #d97706 100%)",
                display: "flex", alignItems: "center", justifyContent: "center",
                fontSize: "3rem", color: "#fff", fontWeight: 900,
                boxShadow: fullSuccess
                  ? "0 0 28px rgba(16,185,129,0.6), 0 8px 24px rgba(0,0,0,0.4)"
                  : "0 0 28px rgba(239,68,68,0.5), 0 8px 24px rgba(0,0,0,0.4)",
                animation: "popIn 0.4s cubic-bezier(0.34, 1.56, 0.64, 1)",
              }}>
                {fullSuccess ? "✓" : hasErrors ? "✕" : "!"}
              </div>
            ) : (
              <div
                style={{
                  width: 78, height: 78, borderRadius: "50%",
                  border: "5px solid rgba(59,143,204,0.18)",
                  borderTopColor: "#3b8fcc",
                  animation: "spin 0.85s linear infinite",
                }}
              />
            )}
            <div style={{ textAlign: "center", maxWidth: 540, padding: "0 24px" }}>
              <div style={{ fontSize: "1.25rem", fontWeight: 800, color: "#fff", marginBottom: 10 }}>
                {done
                  ? saveResult?.total === 0 && (saveResult?.duplicates ?? 0) > 0
                    ? "لا يوجد جديد للحفظ"
                    : fullSuccess
                      ? "اكتمل الحفظ بنجاح"
                      : hasErrors
                        ? "اكتمل الحفظ مع وجود أخطاء"
                        : "اكتمل الحفظ"
                  : "جاري معالجة وتكويد البنود"}
              </div>
              <div style={{ fontSize: "1rem", color: done && fullSuccess ? "#86efac" : "#7ec8f0", lineHeight: 1.8, fontWeight: 700 }}>
                {done && saveResult?.total === 0 && (saveResult?.duplicates ?? 0) > 0 ? (
                  <>
                    جميع البنود (<strong style={{ color: "#fff", fontSize: "1.25rem" }}>{(saveResult?.duplicates ?? 0).toLocaleString("ar-EG")}</strong>) موجودة مسبقاً في قاعدة البيانات — لم تتم إضافة أي صف جديد
                  </>
                ) : (
                  <>
                    تم حفظ <strong style={{ color: "#fff", fontSize: "1.25rem" }}>{arSaved}</strong>
                    {" "}من إجمالي{" "}
                    <strong style={{ color: "#fff", fontSize: "1.25rem" }}>{arTotal}</strong>
                    {" "}بند بنجاح
                    {done && (saveResult?.duplicates ?? 0) > 0 && (
                      <div style={{ fontSize: "0.85rem", color: "#fcd34d", marginTop: 6, fontWeight: 600 }}>
                        + {(saveResult?.duplicates ?? 0).toLocaleString("ar-EG")} صف تم تجاوزه (مكرر)
                      </div>
                    )}
                  </>
                )}
              </div>
              {!done && (
                <div style={{ fontSize: "0.78rem", color: "rgba(255,200,120,0.9)", marginTop: 10, fontWeight: 700 }}>
                  ⚠ يرجى عدم إغلاق المتصفح — كل دفعة محفوظة بشكل دائم في قاعدة البيانات
                </div>
              )}
              {done && hasErrors && saveResult?.firstError && (
                <div style={{ fontSize: "0.78rem", color: "#fca5a5", marginTop: 10, padding: "8px 14px", background: "rgba(239,68,68,0.1)", border: "1px solid rgba(239,68,68,0.3)", borderRadius: 8 }}>
                  {saveResult.firstError}
                </div>
              )}
            </div>

            {/* ── Live Progress Bar ── */}
            <div style={{ width: "min(520px, 80vw)", padding: "0 20px" }}>
              <div style={{
                width: "100%", height: 14,
                background: "rgba(59,143,204,0.12)",
                border: "1px solid rgba(59,143,204,0.25)",
                borderRadius: 999, overflow: "hidden",
                boxShadow: "inset 0 2px 6px rgba(0,0,0,0.45)",
              }}>
                <div style={{
                  width: `${percent}%`, height: "100%",
                  background: "linear-gradient(90deg, #1e6fa8 0%, #3b8fcc 50%, #7ec8f0 100%)",
                  borderRadius: 999,
                  transition: "width 0.35s ease-out",
                  boxShadow: "0 0 14px rgba(126,200,240,0.6)",
                }} />
              </div>
              <div style={{
                display: "flex", justifyContent: "space-between",
                marginTop: 8, fontSize: "0.75rem",
                color: "rgba(255,255,255,0.7)", fontWeight: 700,
              }}>
                <span>{percent}%</span>
                <span>{arSaved} / {arTotal}</span>
              </div>
            </div>

            {done && (
              <button
                onClick={() => { setSaveResult(null); setIsSaving(false); }}
                autoFocus
                style={{
                  marginTop: 8, padding: "12px 36px",
                  background: fullSuccess
                    ? "linear-gradient(135deg, #c5a059 0%, #a88540 100%)"
                    : "linear-gradient(135deg, #3b8fcc 0%, #1e6fa8 100%)",
                  color: "#fff", border: "none", borderRadius: 12,
                  fontSize: "0.95rem", fontWeight: 800,
                  fontFamily: "Tajawal, sans-serif",
                  cursor: "pointer",
                  boxShadow: "0 6px 20px rgba(0,0,0,0.4)",
                  letterSpacing: "0.04em",
                }}
              >تم — إغلاق</button>
            )}

            <style>{`
              @keyframes spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }
              @keyframes popIn { 0% { transform: scale(0.3); opacity: 0; } 100% { transform: scale(1); opacity: 1; } }
            `}</style>
          </div>
        );
      })()}
    </div>
  );
}
