uploads = []
generated = []

[[outputs]]
id = "Be29E4_ln8Rq1nE4sNH49"
uri = "file://rawaf-project.tar.gz"
type = "unspecified"
title = "مشروع الرواف الكامل - rawaf-project.tar.gz"

[[outputs]]
id = "E55wjCLCuKHLBnXH2Uh4d"
uri = "file://rawaf-code-full.txt"
type = "text"
title = "كود مشروع الرواف الكامل - rawaf-code-full.txt"

[[outputs]]
id = "n_M3STB_mHGG_xKLUulRw"
uri = "file://rawaf-setup.txt"
type = "text"
title = "rawaf-setup.js — سكريبت الإعداد التلقائي"

[[outputs]]
id = "3_Es22WtN0V617NeltQaT"
uri = "file://rawaf-full.tar.gz"
type = "unspecified"
title = "مشروع الرواف الكامل — rawaf-full.tar.gz"
