uploads = []
generated = []

[[outputs]]
id = "Be29E4_ln8Rq1nE4sNH49"
uri = "file://rawaf-project.tar.gz"
type = "unspecified"
title = "مشروع الرواف الكامل - rawaf-project.tar.gz"

[[outputs]]
id = "E55wjCLCuKHLBnXH2Uh4d"
uri = "file://rawaf-code-full.txt"
type = "text"
title = "كود مشروع الرواف الكامل - rawaf-code-full.txt"
